# ─────────────────────────────────────────────
# Hardhat — Kitty Theme
# Industrial dark, balanced contrast
#
# Author: g-kirti
# ─────────────────────────────────────────────

### UI

foreground              #b6c2cc
background              #222629

selection_foreground    #121416
selection_background    #d9b100

cursor                  #b6c2cc
cursor_text_color       #222629

scrollbar_handle_color  #3d464c
scrollbar_track_color   #2a2f33

url_color               #4ab0d6

active_border_color     #4ab0d6
inactive_border_color   #2b3135
bell_border_color       #d77d20

macos_titlebar_color    system
wayland_titlebar_color  #222629

active_tab_background   #3d464c
active_tab_foreground   #b6c2cc

inactive_tab_background #2a2f33
inactive_tab_foreground #888888

tab_bar_background      #13171b


### Marked text

mark1_foreground #121416
mark1_background #4ab0d6

mark2_foreground #121416
mark2_background #d9b100

mark3_foreground #121416
mark3_background #d77d20


# ─────────────────────────────────────────────
# ANSI palette
# ─────────────────────────────────────────────

# black
color0  #121416
color8  #646f73

# red
color1  #dc483b
color9  #ea8f86

# green
color2  #bcc313
color10 #cfd55f

# yellow
color3  #d9b100
color11 #f2cd63

# blue    (actually more teal)
color4  #2ca4aa
color12 #62c2c6

# magenta (actually orange)
color5  #d77d20
color13 #f2ab5f

# cyan    (UN blue) 
color6  #4ab0d6
color14 #86c7e3

# white
color7  #a8a8a8
color15 #bebebe

# Additional 
color16 #13171b
