# ─────────────────────────────────────────────
# Hardhat — Light (Kitty)
# Industrial light, blue-shifted neutral
#
# Author: g-kirti
# ─────────────────────────────────────────────

### UI

foreground              #1f262d
background              #e1e7ed

selection_foreground    #121416
selection_background    #d2b24a

cursor                  #1f262d
cursor_text_color       #e1e7ed

scrollbar_handle_color  #5c6874
scrollbar_track_color   #b3bfcc

url_color               #2c689f

active_border_color     #669dd0
inactive_border_color   #c5ced8
bell_border_color       #d78543

macos_titlebar_color    system
wayland_titlebar_color  #e1e7ed

active_tab_background   #f0f4f8
active_tab_foreground   #1f262d

inactive_tab_background #cfd8e1
inactive_tab_foreground #69747f

tab_bar_background      #cfd8e1


### Marked text

mark1_foreground #121416
mark1_background #2c689f

mark2_foreground #121416
mark2_background #b18400

mark3_foreground #121416
mark3_background #b65712


# ─────────────────────────────────────────────
# ANSI palette
# ─────────────────────────────────────────────

# black
color0  #1b2127
color8  #5c6874

# red
color1  #b43229
color9  #dc756b

# green
color2  #789000
color10 #a2ba48

# yellow
color3  #b18400
color11 #d2b24a

# blue    (dark teal)
color4  #197a8f
color12 #55a9bb

# magenta (dark orange)
color5  #b65712
color13 #d78543

# cyan    (UN blue)
color6  #2c689f
color14 #669dd0

# white   (actually bluish-gray)
color7  #2f363e
color15 #4a545e

# Additional
color16 #cfd8e1
