# ─────────────────────────────────────────────
# Hardhat — Diffused (Kitty)
# Muted industrial dark, softened contrast
#
# Author: g-kirti
# ─────────────────────────────────────────────

### UI

foreground              #afbbc4
background              #2a2f33

selection_foreground    #191b1e
selection_background    #c2a004

cursor                  #afbbc4
cursor_text_color       #2a2f33

scrollbar_handle_color  #454f57
scrollbar_track_color   #33393e

url_color               #539fb9

active_border_color     #539fb9
inactive_border_color   #33393e
bell_border_color       #c27727

macos_titlebar_color    system
wayland_titlebar_color  #2a2f33

active_tab_background   #454f57
active_tab_foreground   #afbbc4

inactive_tab_background #33393e
inactive_tab_foreground #7a7e81

tab_bar_background      #191e23


### Marked text

mark1_foreground #191b1e
mark1_background #539fb9

mark2_foreground #191b1e
mark2_background #c2a004

mark3_foreground #191b1e
mark3_background #c27727


# ─────────────────────────────────────────────
# ANSI palette
# ─────────────────────────────────────────────

# black
color0  #191b1e
color8  #717d82

# red
color1  #c3473c
color9  #e18e86

# green
color2  #aeb417
color10 #c9d067

# yellow
color3  #c2a004
color11 #e3c565

# blue    (actually more teal
color4  #36989c
color12 #6ab7bb

# magenta (actually orange)
color5  #c27727
color13 #e2a159

# cyan    (UN blue)
color6  #539fb9
color14 #8ec0d6

# white
color7  #9aa0a4
color15 #b0b4b8

# Additional
color16 #191e23
