wayland_titlebar_color #222629

cursor #c5d0d9

foreground #c5d0d9
background #222629

selection_foreground #131517
selection_background #e3b600

# Black
color0  #131517
color8  #6a767a

# Red
color1  #e84d3f
color9  #f39a90

# Green
color2  #dce30b
color10 #dde46a

# Yellow
color3  #e3b600
color11 #ffd966

# Blue
color4  #31b3b8
color12 #70d0d4

# Magenta
color5  #e8851c
color13 #ffba66

# Cyan
color6  #53bce6
color14 #a0dbf2

# White
color7  #adadad
color15 #d4d4d4

# Additional
color16 #14181c
